# Generated by Django 3.2.8 on 2021-10-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name_p', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('last_name_m', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('ci', models.CharField(max_length=30, verbose_name='Carnet de Identidad')),
                ('age', models.CharField(max_length=3, verbose_name='Edad')),
                ('gender', models.CharField(max_length=9, verbose_name='Sexo')),
                ('origin', models.CharField(max_length=100, verbose_name='Centro de Salud')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Patient',
                'ordering': ['id'],
            },
        ),
    ]
